# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ATeamDojo < Formula
  desc "Terminal dojo for Canvas on-call preparedness (belt-ranked katas + SM-2 review)"
  homepage "https://github.com/drakeaharper/a-team-dojo"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drakeaharper/a-team-dojo/releases/download/v0.2.2/a-team-dojo_darwin_amd64.tar.gz"
      sha256 "85d9642a2013a9f16807eaf23cd144ee89accac55b7002da01fc3cf6ba665195"

      define_method(:install) do
        bin.install "a-team-dojo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drakeaharper/a-team-dojo/releases/download/v0.2.2/a-team-dojo_darwin_arm64.tar.gz"
      sha256 "6f81ce39f8a3a93ab1d1e27fb6f5171d2bfcb41d8228be0af58c4e680266eed3"

      define_method(:install) do
        bin.install "a-team-dojo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drakeaharper/a-team-dojo/releases/download/v0.2.2/a-team-dojo_linux_amd64.tar.gz"
      sha256 "2f06d35a664eb0e7b2ecd71de976cf7121b8e0478945e28b0fadda64b4f857bc"
      define_method(:install) do
        bin.install "a-team-dojo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drakeaharper/a-team-dojo/releases/download/v0.2.2/a-team-dojo_linux_arm64.tar.gz"
      sha256 "b7efd634b950373a3c06beae85b9def0c1f6f75e5a6f91e3343b6bdd3c387222"
      define_method(:install) do
        bin.install "a-team-dojo"
      end
    end
  end

  test do
    system "#{bin}/a-team-dojo", "--help"
  end
end
