# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ATeamDojo < Formula
  desc "Terminal dojo for Canvas on-call preparedness (belt-ranked katas + SM-2 review)"
  homepage "https://github.com/drakeaharper/a-team-dojo"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drakeaharper/a-team-dojo/releases/download/v0.1.1/a-team-dojo_darwin_amd64.tar.gz"
      sha256 "60e80660e4246dda6f6053d3e38b1efc2be1ed0b01dd891e4bf8bde80c17953e"

      define_method(:install) do
        bin.install "a-team-dojo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drakeaharper/a-team-dojo/releases/download/v0.1.1/a-team-dojo_darwin_arm64.tar.gz"
      sha256 "626247225420ec3bee0710413f1400dd757878a98a75b0b867d0fd55332ffa73"

      define_method(:install) do
        bin.install "a-team-dojo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drakeaharper/a-team-dojo/releases/download/v0.1.1/a-team-dojo_linux_amd64.tar.gz"
      sha256 "132a0d0e644b38d54470d16d0ab6538307af000e61436791a4bfe7cba614fc3b"
      define_method(:install) do
        bin.install "a-team-dojo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drakeaharper/a-team-dojo/releases/download/v0.1.1/a-team-dojo_linux_arm64.tar.gz"
      sha256 "0bc55fd1e47ced6f14b061ff3724006f33d2a7a267a8f035ab4c3b711a6b9a01"
      define_method(:install) do
        bin.install "a-team-dojo"
      end
    end
  end

  test do
    system "#{bin}/a-team-dojo", "--help"
  end
end
