# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jet < Formula
  desc "A CLI tool for Jira workflow management"
  homepage "https://github.com/drakeaharper/ira-jet"
  version "1.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drakeaharper/jira-jet/releases/download/v1.12.0/jet_darwin_amd64.tar.gz"
      sha256 "76cea43042b30eb3f5d3ac20661427d7b31fd22b18536b3300407211184f1e0b"

      define_method(:install) do
        bin.install "jet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drakeaharper/jira-jet/releases/download/v1.12.0/jet_darwin_arm64.tar.gz"
      sha256 "c711e29dfd9051a0b207d1db17e84d43dadd6609be337d16cd575b2ee87fe436"

      define_method(:install) do
        bin.install "jet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drakeaharper/jira-jet/releases/download/v1.12.0/jet_linux_amd64.tar.gz"
      sha256 "b1ca0297cffc38ae730a2d98f4bc431a228fbdbf3bf7c5ce51ed28aea1e90f06"
      define_method(:install) do
        bin.install "jet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drakeaharper/jira-jet/releases/download/v1.12.0/jet_linux_arm64.tar.gz"
      sha256 "f8bab8e3ee32c23b5b1b94147305c5a6217fc484e1e0dbbae5ad5b632a99b2ed"
      define_method(:install) do
        bin.install "jet"
      end
    end
  end

  test do
    system "#{bin}/jet", "--help"
  end
end
